### ISSUE TITLE
Guia de contribuição ou CONTRIBUTING.md

### ISSUE THREAD

**Issue by firminochangani** [codingdojoangola/portaldev#10]
Sendo um projecto grande e com um project leader ( @JoseCage ), acredito que um guia de como contribuir iria nos ajudar a interagir e contribuir melhor com o projecto. Tópicos relevantes:

1 - Quando abrir issue
2 - Como fazer o pull request (que branch)

Ex: https://github.com/atom/atom/blob/master/CONTRIBUTING.md
Mais sobre: https://github.com/blog/1184-contributing-guidelines

Longa vida ao CdA. :) Thanks.

**Comment by JoseCage** [comment]
@flowck Obrigado pela sugestão. Vou criar neste exato momento, para facilitar aos contribuidores/desenvolvedores a saber como colaborar e quais são os **Padrões**..

- [ ] De que forma contribuir 

- [ ] Como sincronizar o fork com o repositório original 

- [ ] Modelo de _branching_ (nomeação de **branchs**)

**Comment by JoseCage** [comment]
@flowck Adicionei o `CONTRIBUTING.md`. Como fiz uma alteração do que eu havia colocado no[ doesangue](https://github.com/doesangueorg/doesangue-core) então coloquei a versão em inglês..

**Comment by JoseCage** [comment]
Atendendo que já se adicionou o `CONTRIBUTING.md` vou fechar a issue... Valeu a sugestão @flowck
