### ISSUE TITLE
Estrutura e funcionalidades do portal

### ISSUE THREAD

**Issue by JoseCage** [codingdojoangola/portaldev#6]
Como forma de organizar em etapas as funcionalidades do app e igualmente sabermos melhor basear em cada funcionalidade para criar os desafios irei anotar abaixo a estrutura do projeto em si e as funcionalidades que o mesmo deve "ter" a curto e a longo prazo..

Seguindo a própria estrutura de diretórios do **[Laravel](https://laravel.com/docs/5.5/structure)** apenas faremos algumas alteração, como colocar todos models dentro de `app/Models`, exemplo o model **User** `app/Models/User.php`.

Abaixo a lista de diretórios/pastas onde "em maioria" iremos trabalhar no decorrer do desenvolvimento..

 ```
* app
   - Events (Diretório onde ficarão todas Classes para trabalhar com eventos na app)
   - Http
      - Controllers (Diretório onde ficarão os controllers [algoritmos das funcionalidades])
      - Requests (Classes de Validação de requests dentro da app)
   - Listeners  (Classes que trabalham com eventos, interceptando sempre que  um evento for disparado)
   - Mail (Classes que trabalharão com envios de email)
   - Notifications (Similar à Mail, mas mais voltado para notificações [exp: sms, slack])
   - Providers (Provedores de serviço, exemplo: caso venhamos a criar um gateway dentro do app, o ServiceProvider deste gateway ficará aqui)
* database
   - migrations (Tabelas que compõe o banco de dados de uma forma simples e organizada)
   - seeds (Dados estáticos para testes, dados gerados usando Faker)
 resources
  - assets
    - js (Todo código javascript referente ao frontend fda plataforma fica aqui)
    - sass
  - lang (Ficheiros de línguas/tradução que terão suporte no app. Padrão: *pt*)
  - views (Todos ficheiros relacionados a estrutura html (frontend) fica aqui)
```
------------------------
## Funcionalidades

- [ ] Autenticação
  - [x] Cadastro com e-mail e senha
  - [x] Login com usuário/e-mail e senha 
  - [ ] Confirmação da conta via **e-mail** ou **sms** ao cadastrar 
  - [ ] Recuperação da conta e redefinição de senha 
  - [ ] Cadastro/Login com redes sociais
  - [ ] Autenticação em dois factores ([2FA](https://www.securenvoy.com/two-factor-authentication/what-is-2fa.shtm))
  - [ ] Controle de acesso dos dispositivos conectados (dispositivos onde o usuário tem sessão iniciada)
  - [ ] Níveis de acesso
      - [ ] Apenas a empresa que publicou a vaga pode editar e ver resultados
      - [ ] Limitar acesso a certas funções com base no nível de acesso do usuário

- [ ] Vagas, Projetos
    - [ ] Permitir a empresa criar vaga/projeto
    - [ ] Permitir ao freelancer visual vagas/projetos publicados
    - [ ] Permitir ao freelancer enviar proposta para empresa apenas dentro da plataforma
    - [ ] Empresa pode visualizar e avaliar cada proposta que receber
- [ ] Certificados
    - [ ] Gerar certificado digital (comprovando habilidade do freelancer na plataforma)
    - [ ] Validar certificado pelo "**código único de identificação**"
    - [ ] Invalidar certificado caso o usuário cometa alguma irregularidade 
    - [ ] Permitir ao usuário (freelancer ou empresa) solicitar a emissão de certificado

---------------------------------------------------------

Qualquer dúvida referente ao Laravel só comentar ou abrir uma [issue](https://github.com/codingdojoangola/portaldev/issues/new)..

**Comment by nelsonmfinda** [comment]
Wow idea mui boa (y) não o portal não terá uma app mobile?

**Comment by JoseCage** [comment]
> o portal não terá uma app mobile?

@Orizon98  Sim terá. Mas a principio o desafio é fazer a plataforma web. Conseqüentemente criaremos uma **API** que irá servir os dados para o mobile.

**Comment by Santiago44325** [comment]
É uma honra fazer parte deste projecto ..!

**Comment by JoseCage** [comment]
@Santiago44325  qualquer dificuldade basta abrir um ticket (`issue`) ou mesmo interagir aqui que é o ticket principal. Ou ainda pelo slack.

Mas como é um projeto open o ideal é deixar o máximo de informação aqui no **GH**..
