### ISSUE TITLE
Enviar email de confirmação e boas vindas a cada novo usuário

### ISSUE THREAD

**Issue by JoseCage** [codingdojoangola/portaldev#7]
Desafio| Complexidade | Atribuido à |
|---| ---| ---|
Enviar email de confirmação e boas vindas a cada novo usuário | médio | @Orizon98 
---------------------

O desafio é criar uma função (**ATT**: _Seguindo os padrões do Laravel_) que monitora o cadastro de novos usuários e envia um email com o link de confirmação/ativação da conta para o endereço indicado no cadastro..

- [ ] Criar o [evento](https://laravel.com/docs/5.5/events) `UserRegistered` :ear: 
 Para monitorar novos cadastros

- [ ] Criar o [Listener](https://laravel.com/docs/5.5/events#defining-listeners) `UserRegisteredListener` 
 Mesmo propósito que o `UserRegistered` :point_up: 

- [ ] Criar o [Mailer](https://laravel.com/docs/5.5/mail) `UserConfirmation` :incoming_envelope: 
  Para enviar o email com o link de confirmação ao usuário

- [ ] Criar o evento `UserConfirmated` :ear: 
 Para monitorar caso um usuário confirmar o cadastro e enviar email de boas-vindas :point_down: 

- [ ] Criar o Mailer `UserWelcome` :incoming_envelope: 
  Para enviar o email de boas vindas ao usuário depois que confirmar o cadastro

**Comment by nelsonmfinda** [comment]
Podemos começar já? Antes da reunião!

**Comment by JoseCage** [comment]
> Podemos começar já? Antes da reunião!

De certeza @Orizon98. A reunião é para escolha do nome..

Alias, eu já comecei.. Este ticket ja estou a criar as funcionalidades..

Vou abrir outro ticket sobre mais funcionalidades..

**Comment by JoseCage** [comment]
Em todo caso @Orizon98 no ticket #6 tem a ideia geral do que poderá ter na plataforma (embora ainda não listei tudo lá).

**Comment by JoseCage** [comment]
@Orizon98 Atribui à ti a tarefa de resolver este ticket..

Obrigado pela participação..

**Comment by JoseCage** [comment]
Alguma novidade quanto ao `ticket`, @Orizon98????
